### PR TITLE
Other minor update

### PR DESCRIPTION
**Pull request by klich3**
Sorry to distract you again, I've run into little details:

Minor update on readme file
Added correct structure for Examples
Correct "check_files" option type of declaration

Regards,
Anton

### CODE REVIEW

**Comment by paragi** [comment]
Feel free to merge the PR your self :)

**Comment by klich3** [comment]
Hi Simon, I just got the invitation. Thank you very much for trusting me with the project.

**Comment by paragi** [comment]
Hi Anton
I'm having difficulty finding the time to maintaining a lot of modules at present. I really appreciate that you can contribute and expand on it. I hope you will also handle any problems with your modification if they should occur :)
BR Simon

**Comment by klich3** [comment]
Hi Simon, of course, as I use the library and according to the ideas I have I will expand and maintain the repo.
Thanks again for your trust

**Comment by paragi** [comment]
Thanks, it is very much appreciated :)

**Pull request merged**
