### PR TITLE
Minor bugfixes

### PR DESCRIPTION
**Pull request by klich3**
Hi there,
Solve bug fixes, removed necessary folders from ignore. Updated the Readme a bit.

Regards.

### CODE REVIEW

**Comment by paragi** [comment]
Thank you for your contribution. it's very nice code.
You are very welcome to insert your name as author of new code and as contributor when refactoring, and take credit for you good work.
However I think you are a little too free with the copyrights, when you are changing existing code. 
I'm sure its just a matter of habit. But please don't overdo it.
I'm looking forward to accept you pull request.

**Comment by klich3** [comment]
Thanks for accepting the changes, I really liked the idea, and the simplicity of the code. It could be implemented in several things. I apologize for the tags, as they are inserted automatically. 

In a few moments I will make the correction.

Best regards.

**Comment by klich3** [comment]
Now all comments are as they should be.
Regards

**Comment by paragi** [comment]
Thanks a lot. So nice that someone else can bring in new things. Especially when I'm too hung op to do the maintenance.

**Pull request merged**
